import Send from '../svg/send.svg'

export const Icons = {
    heart: require('./heart.png'),
    instagram: require('./instagram.png'),
    instagramText: require('./instagram_text_logo.png'),
    send: require('./send.png'),
    sendHorizontal: require('./send_hori.png'),
    sendSVG: Send,
    heartFill: require('./heartFill.png'),
    bookMark: require('./bookmark.png'),
    chat: require('./chat.png'),
    moreVert: require('./more_vert.png'),
    more: require('./more.png'),
    home: require('./home.png'),
    search: require('./search.png'),
    reel: require('./reel.png'),
    plus: require('./plus.png'),
    homeFill: require('./home_fill.png'),
    searchFill: require('./search_fill.png'),
    reelFill: require('./reel_fill.png'),
    back: require('./back.png'),
    next: require('./next.png'),
    clear: require('./clear.png'),
    zoomIn: require('./zoom_in.png'),
    zoomOut: require('./zoom_out.png'),
}